name: Weather Telegram Bot
 
on:
  schedule:
    - cron: "*/10 * * * *"  # Every 10 mins
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
      - name: Update Weather Information
        env:
          TAMP_API_KEY: ${{ secrets.TAMP_API_KEY }} 
          TAMP_CHAT_ID: ${{ secrets.TAMP_CHAT_ID }}
          BP_API_KEY: ${{ secrets.BP_API_KEY }} 
          BP_CHAT_ID: ${{ secrets.BP_CHAT_ID }}
        run: |
          python src/tamp_weather_bot.py
          python src/bp_weather_bot.py
      
      - name: Check if there are any new changes
        id: verify_diff
        run: |
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT
      
      - name: Commit

        if: steps.verify_diff.outputs.changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git pull
          git add .
          git commit -m "Updated Telegram Bot" -a
          git push
